# Generated by Django 4.0.2 on 2022-10-04 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20220803_0459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalticket',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ticket'},
        ),
        migrations.AlterModelOptions(
            name='historicaluser',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical user'},
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='data_bucket_name',
            field=models.CharField(blank=True, default='', help_text='Name of Cloud Data Bucket', max_length=250, verbose_name='Data Bucket Name'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='jira_id',
            field=models.CharField(blank=True, default='', help_text='Associated Jira Ticket ID', max_length=100, verbose_name='Associated Jira Ticket ID'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='data_bucket_name',
            field=models.CharField(blank=True, default='', help_text='Name of Cloud Data Bucket', max_length=250, verbose_name='Data Bucket Name'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='jira_id',
            field=models.CharField(blank=True, default='', help_text='Associated Jira Ticket ID', max_length=100, verbose_name='Associated Jira Ticket ID'),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='consent_code',
            field=models.CharField(default='', help_text='Please refer to Data Custodian Instructions for more information', max_length=100, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9.]{0,59}[a-z0-9]$', 'dbGaP Consent Group Code format invalid')], verbose_name='dbGaP Consent Group Code'),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='consent_code',
            field=models.CharField(default='', help_text='Please refer to Data Custodian Instructions for more information', max_length=100, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9.]{0,59}[a-z0-9]$', 'dbGaP Consent Group Code format invalid')], verbose_name='dbGaP Consent Group Code'),
        ),
    ]
