# Generated by Django 3.2.9 on 2021-12-14 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_auto_20211116_1642"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ticket_review_comment",
            field=models.TextField(
                default="",
                help_text="Please provide a comment for approval or rejection",
                max_length=2500,
                verbose_name="Ticket Review Comment",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="aws_iam",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If you're uploading to Amazon please provide your AWS IAM (ex: arn:aws:iam::123456789012:user/username)",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "arn:aws:iam::[0-9]{12}:user/[a-zA-Z0-9-_]{1,64}",
                        "AWS IAM format invalid",
                    )
                ],
                verbose_name="AWS IAM",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="consent_code",
            field=models.CharField(
                default="", max_length=100, verbose_name="Consent Code"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="data_size",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Please provide an estimated size of your data set(s)",
                max_length=100,
                verbose_name="Data Size",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="dataset_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Describe the dataset you are uploading",
                max_length=2500,
                verbose_name="Dataset Description",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="email",
            field=models.EmailField(default="", max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="google_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="If you're uploading to Google please provide your google email for access",
                max_length=254,
                verbose_name="Google Email",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="is_test_data",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Check this box if this is test data",
                verbose_name="Is Test Data",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="name",
            field=models.CharField(
                default="",
                help_text="Name of primary contact",
                max_length=100,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="organization",
            field=models.CharField(
                default="",
                help_text="Name of requesting organization",
                max_length=250,
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="study_id",
            field=models.CharField(default="", max_length=100, verbose_name="Study ID"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="study_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of Study or Dataset (if applicable)",
                max_length=250,
                verbose_name="Study Name",
            ),
        ),
    ]
