# Generated by Django 4.0.2 on 2022-10-06 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_historicalticket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='aws_iam',
            field=models.CharField(blank=True, default='', help_text="If you're uploading to Amazon, please provide your AWS IAM ARN (ex: arn:aws:iam::123456789012:user/username)", max_length=100, validators=[django.core.validators.RegexValidator('^arn:aws:iam::[0-9]{12}:user/[a-zA-Z0-9-_]{1,64}$', 'AWS IAM format invalid. Please use the following format: arn:aws:iam::123456789012:user/username')], verbose_name='AWS IAM'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='aws_iam',
            field=models.CharField(blank=True, default='', help_text="If you're uploading to Amazon, please provide your AWS IAM ARN (ex: arn:aws:iam::123456789012:user/username)", max_length=100, validators=[django.core.validators.RegexValidator('^arn:aws:iam::[0-9]{12}:user/[a-zA-Z0-9-_]{1,64}$', 'AWS IAM format invalid. Please use the following format: arn:aws:iam::123456789012:user/username')], verbose_name='AWS IAM'),
        ),
    ]
