# Generated by Django 4.0.2 on 2022-02-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_ticket_bucket_created_by_ticket_data_accepted_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='data_upload_completed_by',
            new_name='data_uploaded_completed_by',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='data_upload_started_by',
            new_name='data_uploaded_started_by',
        ),
    ]
