# Generated by Django 4.1.4 on 2023-07-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_historicalticket_aws_iam_alter_ticket_aws_iam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalticket',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ticket', 'verbose_name_plural': 'historical tickets'},
        ),
        migrations.AlterModelOptions(
            name='historicaluser',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical user', 'verbose_name_plural': 'historical users'},
        ),
        migrations.RemoveField(
            model_name='historicalticket',
            name='data_bucket_name',
        ),
        migrations.RemoveField(
            model_name='historicalticket',
            name='jira_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='data_bucket_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='jira_id',
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
