# Generated by Django 3.2.9 on 2021-12-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20211214_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_review_comment',
            field=models.CharField(blank=True, default='', help_text='Please provide a comment for approval or rejection', max_length=1000, verbose_name='Ticket Review Comment'),
        ),
    ]
