# Generated by Django 4.0 on 2021-12-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_ticket_data_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='data_unit',
        ),
    ]
