# Generated by Django 4.0 on 2021-12-21 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_ticket_data_size_alter_ticket_data_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='data_unit',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='data_size',
            field=models.CharField(default='', help_text='Please provide an estimated size of your data set(s)', max_length=100, validators=[django.core.validators.RegexValidator('^[0-9]{1,5} (MB|GB|TB|PB)$', 'Data Size must be a number')], verbose_name='Data Size'),
        ),
    ]
